version: '3'

services:
  geth:
    image: ethereum/client-go:v1.8.27
    volumes:
      - ./data:/data
    ports:
      - '8545:8545'
      - '30303:30303'
      - '30303:30303/udp'
    command:
      - --datadir=/data
      - --networkid=3
      - --syncmode=fast
      - --rpc
      - --rpcaddr=0.0.0.0
      - --rpcvhosts=*
      - --rpcapi=web3,eth,admin,net,txpool,db,debug
      - --maxpeers=25
      - --testnet

    restart: always

  exporter:
    image: 4ops/ethereum-exporter:v0.1.0
    ports:
      - '9144:9144'
    depends_on:
      - geth
    links:
      - geth
    environment:
      ETHEREUM_API_URL: http://geth:8545
      METRICS_PREFIX: geth_
      LOG_LEVEL: info
    restart: always
