version: '3'

services:
  ethereum:
    restart: 'no'
    network_mode: host

  exporter:
    build: .
    env_file: docker/.env
    depends_on:
      - ethereum
    network_mode: host
    restart: 'no'
