#
# It's just an example! Edit this file before deploy to kubernetes cluster!
#
apiVersion: v1
stringData:
  ETHEREUM_API_URL: 'http://parity:8545'
kind: Secret
metadata:
  name: ethereum-exporter
  namespace: testing
type: Opaque
