#
# It's just an example! Edit this file before deploy to kubernetes cluster!
#
apiVersion: v1
kind: Service
metadata:
  name: parity-ethereum
  namespace: testing
spec:
  ports:
    - name: rpc
      port: 80
      protocol: TCP
      targetPort: 8545
  selector:
    k8s-app: parity
    blockchain: ropsten
  sessionAffinity: None
  type: ClusterIP
# If you need to expose p2p port, create service by example below.
# See additional info: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: parity-ropsten-p2p
#   namespace: testing
# spec:
#   ports:
#   - name: p2p
#     port: 30303
#     protocol: TCP
#     targetPort: 30303
#   - name: p2p-udp
#     port: 30303
#     protocol: UDP
#     targetPort: 30303#   selector:
#     k8s-app: parity
#     blockchain: ropsten
#   sessionAffinity: None
#   type: LoadBalancer
